import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/layouts/main-layout";

const lato = Lato({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "WatchListify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
