import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import ReactQueryWrapper from "@/components/react-query-wrapper";
import MainLayout from "@/components/layouts/main-layout";
import SessionWrapper from "@/components/SessionWrapper";

const lato = Lato({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "WatchListify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={lato.className}>
          <ReactQueryWrapper>
            <MainLayout>{children}</MainLayout>
          </ReactQueryWrapper>
        </body>
      </html>
    </SessionWrapper>
  );
}
